// SPDX-License-Identifier: GPL-3.0-only
// Night studio for Swift (ios/prd.json conventions.design): reads the
// :root block of src/renderer/tokens.css and writes the same colors as a
// Swift enum, so the iPhone app and the desktop app change color
// together. scripts/ios.js writes the result into ios/Generated, which
// is never committed.

const HEX = /^#([0-9a-f]{3}|[0-9a-f]{6}|[0-9a-f]{8})$/i
const RGB = /^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+)\s*)?\)$/i

/** [r, g, b, a] with r, g, b in 0 to 255 and a in 0 to 1, or null for a non-color. */
function parseColor(value) {
  const v = value.trim()
  const hex = v.match(HEX)
  if (hex) {
    let h = hex[1]
    if (h.length === 3) h = [...h].map((c) => c + c).join('')
    const byte = (i) => parseInt(h.slice(i, i + 2), 16)
    const alpha = h.length === 8 ? Math.round((byte(6) / 255) * 1000) / 1000 : 1
    return [byte(0), byte(2), byte(4), alpha]
  }
  const rgb = v.match(RGB)
  if (rgb) return [Number(rgb[1]), Number(rgb[2]), Number(rgb[3]), rgb[4] === undefined ? 1 : Number(rgb[4])]
  return null
}

/** The color tokens of the plain :root block, in file order. Fonts and
 *  anything else that is not a color are skipped; themes are ignored. */
function parseRootTokens(css) {
  const start = css.indexOf(':root {')
  if (start < 0) throw new Error('tokens.css has no :root block')
  const end = css.indexOf('\n}', start)
  const body = css.slice(start, end < 0 ? undefined : end).replace(/\/\*[\s\S]*?\*\//g, '')
  const tokens = []
  for (const match of body.matchAll(/--([a-z0-9-]+)\s*:\s*([^;]+);/gi)) {
    const rgba = parseColor(match[2])
    if (rgba) tokens.push({ name: match[1], rgba })
  }
  return tokens
}

/** panel-lift becomes panelLift. */
function camel(name) {
  return name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
}

const decimal = (n) => (Number.isInteger(n) ? `${n}.0` : String(n))

function toSwift(tokens) {
  const lines = tokens.map(
    ({ name, rgba: [r, g, b, a] }) =>
      `    /// --${name}\n    static let ${camel(name)} = Color(.sRGB, red: ${r}.0 / 255, green: ${g}.0 / 255, blue: ${b}.0 / 255, opacity: ${decimal(a)})`
  )
  return [
    '// SPDX-License-Identifier: GPL-3.0-only',
    '// Generated by scripts/ios.js from src/renderer/tokens.css. Do not edit:',
    '// change tokens.css, and both apps change together.',
    'import SwiftUI',
    '',
    'enum Tokens {',
    ...lines,
    '}',
    ''
  ].join('\n')
}

/** An asset catalog color set (the launch screen's ground). */
function colorSetJson([r, g, b, a]) {
  const unit = (n) => (n / 255).toFixed(3)
  return (
    JSON.stringify(
      {
        colors: [
          {
            color: { 'color-space': 'srgb', components: { red: unit(r), green: unit(g), blue: unit(b), alpha: a.toFixed(3) } },
            idiom: 'universal'
          }
        ],
        info: { author: 'xcode', version: 1 }
      },
      null,
      2
    ) + '\n'
  )
}

module.exports = { parseColor, parseRootTokens, camel, toSwift, colorSetJson }
