#!/usr/bin/env node
// SPDX-License-Identifier: GPL-3.0-only
// Generates THIRD-PARTY-NOTICES.md for the code murmur actually ships:
// runtime dependencies plus the renderer libraries bundled into out/.
// Dev-only tooling (electron-builder, vitest, vite) never ships and is
// deliberately excluded.
const { existsSync, readFileSync, writeFileSync } = require('node:fs')
const { join } = require('node:path')

const root = join(__dirname, '..')

// Seeds: runtime dependencies from package.json, the renderer libraries
// bundled into out/, and the Electron shell itself. The tree walk below
// pulls in every transitive runtime dependency (like uiohook-napi's
// node-gyp-build loader) so nothing that ships goes unlisted.
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
const SEEDS = [...Object.keys(pkg.dependencies ?? {}), 'react', 'react-dom', 'electron']

// electron is a leaf: what ships is its prebuilt binary, not its npm
// dependencies (those are download tooling that never enters a build).
const LEAVES = new Set(['electron'])

function collectShipped(seeds) {
  const seen = new Set()
  const queue = [...seeds]
  while (queue.length > 0) {
    const name = queue.shift()
    if (seen.has(name)) continue
    seen.add(name)
    if (LEAVES.has(name)) continue
    const metaFile = join(root, 'node_modules', name, 'package.json')
    if (!existsSync(metaFile)) continue
    const meta = JSON.parse(readFileSync(metaFile, 'utf8'))
    for (const dep of Object.keys(meta.dependencies ?? {})) queue.push(dep)
  }
  return [...seen].sort()
}

const SHIPPED = collectShipped(SEEDS)

function licenseTextFor(pkg) {
  const dir = join(root, 'node_modules', pkg)
  for (const name of ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'LICENSE-MIT.txt']) {
    const file = join(dir, name)
    if (existsSync(file)) return readFileSync(file, 'utf8').trim()
  }
  return null
}

const sections = []
for (const pkg of SHIPPED) {
  const metaFile = join(root, 'node_modules', pkg, 'package.json')
  if (!existsSync(metaFile)) {
    console.error(`gen-notices: ${pkg} not installed`)
    process.exit(1)
  }
  const meta = JSON.parse(readFileSync(metaFile, 'utf8'))
  const text = licenseTextFor(pkg)
  sections.push(
    [
      `## ${meta.name} ${meta.version}`,
      '',
      `License: ${meta.license ?? 'see text below'}`,
      meta.homepage ? `Homepage: ${meta.homepage}` : null,
      '',
      text ? '```\n' + text + '\n```' : '(license text ships inside the package)',
      ''
    ]
      .filter((line) => line !== null)
      .join('\n')
  )
}

const out = [
  '# Third-party notices',
  '',
  'murmur is GPL-3.0-only (see LICENSE). Builds additionally contain the',
  'following third-party software, reproduced here with their licenses.',
  'Generated by scripts/gen-notices.js; regenerate after dependency bumps.',
  '',
  sections.join('\n')
].join('\n')

writeFileSync(join(root, 'THIRD-PARTY-NOTICES.md'), out)
console.log(`THIRD-PARTY-NOTICES.md written for ${SHIPPED.length} shipped packages`)
