#!/usr/bin/env node
// SPDX-License-Identifier: GPL-3.0-only
// Generates THIRD-PARTY-NOTICES.md for the code murmur actually ships:
// runtime dependencies plus the renderer libraries bundled into out/.
// Dev-only tooling (electron-builder, vitest, vite) never ships and is
// deliberately excluded.
const { existsSync, readFileSync, writeFileSync } = require('node:fs')
const { join } = require('node:path')

const root = join(__dirname, '..')

// Everything that ends up inside a distributed build.
const SHIPPED = ['uiohook-napi', 'react', 'react-dom', 'scheduler', 'electron']

function licenseTextFor(pkg) {
  const dir = join(root, 'node_modules', pkg)
  for (const name of ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'LICENSE-MIT.txt']) {
    const file = join(dir, name)
    if (existsSync(file)) return readFileSync(file, 'utf8').trim()
  }
  return null
}

const sections = []
for (const pkg of SHIPPED) {
  const metaFile = join(root, 'node_modules', pkg, 'package.json')
  if (!existsSync(metaFile)) {
    console.error(`gen-notices: ${pkg} not installed`)
    process.exit(1)
  }
  const meta = JSON.parse(readFileSync(metaFile, 'utf8'))
  const text = licenseTextFor(pkg)
  sections.push(
    [
      `## ${meta.name} ${meta.version}`,
      '',
      `License: ${meta.license ?? 'see text below'}`,
      meta.homepage ? `Homepage: ${meta.homepage}` : null,
      '',
      text ? '```\n' + text + '\n```' : '(license text ships inside the package)',
      ''
    ]
      .filter((line) => line !== null)
      .join('\n')
  )
}

const out = [
  '# Third-party notices',
  '',
  'murmur is GPL-3.0-only (see LICENSE). Builds additionally contain the',
  'following third-party software, reproduced here with their licenses.',
  'Generated by scripts/gen-notices.js; regenerate after dependency bumps.',
  '',
  sections.join('\n')
].join('\n')

writeFileSync(join(root, 'THIRD-PARTY-NOTICES.md'), out)
console.log(`THIRD-PARTY-NOTICES.md written for ${SHIPPED.length} shipped packages`)
